# Generated by Django 2.2.5 on 2021-05-23 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='post_images/', validators=[django.core.validators.FileExtensionValidator(['py', 'ipynb', 'jpg', 'png'])], verbose_name='添付ファイル'),
        ),
    ]
