# Generated by Django 2.2.5 on 2021-05-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descrition',
            new_name='description',
        ),
    ]
