# Generated by Django 3.1.2 on 2021-06-06 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210531_2234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'ブログ', 'verbose_name_plural': 'ブログ'},
        ),
    ]
