# Generated by Django 3.1.2 on 2021-06-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
